### ISSUE TITLE
payload_length_bytes should not assert

### ISSUE THREAD

**Issue by miguel1117** [dsiganos/xnolib#70]
https://github.com/dsiganos/xnolib/blob/338555b603c3dd9b06f9f1420ad0333c5f8a6fc0/pynanocoin.py#L224-L261
Since message header objects are created from data received from external sources, unknown message types can be received. Therefore, this is a runtime error and not a coding bug and the type of the message shouldn't asserted.

**Comment by dsiganos** [comment]
Yes, we have a several asserts in places where we should have a runtime check instead.
